on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stage:
        required: true
        default: https://example.com

env:
  STAGE: ${{ inputs.stage || 'dev' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy $env.STAGE
    environment:
      name: ${{ env.STAGE }}
    steps:
      - name: Test API_URL environment variable
        run: echo stage  ${{ env.STAGE }}
