on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stage:
        required: true
        default: https://example.com
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy $env.STAGE
    env:
      STAGE: ${{ inputs.stage || 'dev' }}
    environment:
      name: ${{ STAGE }}
    steps:
      - name: Test API_URL environment variable
        run: echo stage  ${{ env.STAGE }}
