on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      API_URL:
        required: true
        default: https://example.com

env:
  STAGE: ${{ inputs.stage || 'dev' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test API_URL environment variable
        run: echo stage  ${{ inputs.stage }}
