name: Receiver

on:
  repository_dispatch:
    types: [qa-tests]

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: A event received
        run: |
          echo "payload Foo '${{ github.event.client_payload.foo }}'"

      # Run Unit tests and Coverage
      - name: Unit Tests and Coverage
        run: |
          npm run test
